spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/computerStore?allowPublicKeyRetrieval=true&useSSL=false&createDatabaseIfNotExist=true&serverTimezone=UTC
    username: root
    password:
  mvc:
    hiddenmethod:
      filter:
        enabled: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true
  #    show_sql: true
  sql:
    init:
      mode: never
  security:
    oauth2:
      client:
        registration:
          facebook:
            client-id: 1277767399626116
            client-secret: ${FACEBOOK_LOGIN_SECRET}

server:
  error:
    whitelabel:
      enabled: false
    path: /error

app:
  default:
    admin:
      password: 11111

#Cloudinary properties
cloudinary:
  cloud_name: "dtfd8gw16"
  api_key: "218356847735493"
  api_secret: ${CLOUDINARY_SECRET}

#logging:
#  level:
#    org.springframework: DEBUG   #debugging while logging more info
#    org.hibernate.SQL: DEBUG
#    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
